name: finances
description: App principal de finanças pessoais.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  dependencies:
    path: ../../packages/dependencies
  accounts:
    path: ../../packages/accounts
  local_storage:
    path: ../../packages/local_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true