name: dependencies
description: Pacote para gerenciar dependências externas comuns do workspace.
publish_to: none
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_riverpod: ^2.0.0
  go_router: ^7.0.0
  dio: ^5.0.0
  uuid: ^4.0.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  logger: ^2.6.0


dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.8.0
